import { StyleSheet } from 'react-native';

const globalStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    paddingHorizontal: 24,
    paddingTop: 56,
    alignItems: 'center',
  },
  logoWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 30,
  },
  logo: {
    width: 120,
    height: 120,
    resizeMode: 'contain',
  },
  formCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: '#e8e8e8',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
  },
  form: {
    width: '100%',
  },
  inputGroup: {
    marginBottom: 14,
  },
  input: {
    width: '100%',
    height: 52,
    borderWidth: 1,
    borderColor: '#dfe3e8',
    borderRadius: 12,
    backgroundColor: '#f9fafb',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: '#1f2937',
  },
  inputRow: {
    position: 'relative',
    justifyContent: 'center',
  },
  passwordInput: {
    paddingRight: 44,
  },
  eyeButton: {
    position: 'absolute',
    right: 12,
    top: 12,
    padding: 6,
  },
  eyeText: {
    fontSize: 20,
    color: '#6b7280',
  },
  linkButton: {
    alignSelf: 'flex-end',
    marginBottom: 18,
    marginTop: 4,
  },
  linkText: {
    color: '#1b4bbf',
    fontSize: 14,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  primaryButton: {
    width: '100%',
    height: 52,
    borderRadius: 12,
    backgroundColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  primaryButtonDisabled: {
    backgroundColor: '#b6bac3',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  primaryButtonTextDisabled: {
    color: '#eef2f7',
  },
  secondaryButton: {
    width: '100%',
    height: 52,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
  },
  secondaryButtonText: {
    color: '#0f172a',
    fontSize: 16,
    fontWeight: '600',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  modalCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 20,
    borderWidth: 1,
    borderColor: '#ebebeb',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 6,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 8,
  },
  modalText: {
    fontSize: 14,
    color: '#475467',
    marginBottom: 12,
  },
  modalInput: {
    width: '100%',
    height: 48,
    borderWidth: 1,
    borderColor: '#dfe3e8',
    borderRadius: 10,
    backgroundColor: '#f9fafb',
    paddingHorizontal: 12,
    fontSize: 15,
    color: '#1f2937',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 16,
  },
  modalButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginLeft: 10,
  },
  modalButtonPrimary: {
    backgroundColor: '#0f172a',
  },
  modalButtonSecondary: {
    backgroundColor: '#eef2ff',
  },
  modalButtonTextPrimary: {
    color: '#ffffff',
    fontWeight: '700',
  },
  modalButtonTextSecondary: {
    color: '#0f172a',
    fontWeight: '600',
  },
  homePage: {
    flex: 1,
    backgroundColor: '#f5f5f5',
    paddingHorizontal: 24,
    paddingTop: 56,
    paddingBottom: 120,
  },
  homeContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: '#0f172a',
  },
  bottomNavWrapper: {
    position: 'absolute',
    left: 20,
    right: 20,
    bottom: 24,
    alignItems: 'center',
  },
  glassNavBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    width: '100%',
    height: 78,
    borderRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.48)',
    borderColor: 'rgba(255,255,255,0.8)',
    borderWidth: 1,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 8,
    paddingHorizontal: 16,
  },
  navItem: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  navItemActive: {
    backgroundColor: 'rgba(107, 114, 128, 0.38)',
    borderWidth: 1,
    borderColor: 'rgba(75, 85, 99, 0.55)',
    shadowColor: '#4b5563',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 5,
  },
  navIcon: {
    fontSize: 24,
    color: '#1f2937',
    lineHeight: 28,
  },
  navIconActive: {
    color: '#1f2937',
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#475467',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  schedulePage: { flex: 1, backgroundColor: '#f3f6f4' },
  scheduleContent: { paddingHorizontal: 20, paddingTop: 58, paddingBottom: 132 },
  scheduleEyebrow: { color: '#3e7185', fontSize: 12, fontWeight: '800', letterSpacing: 1.1, textTransform: 'uppercase' },
  scheduleTitle: { color: '#17324d', fontSize: 32, fontWeight: '800', marginTop: 5, marginBottom: 18 },
  calendarCard: { backgroundColor: '#ffffff', borderRadius: 22, padding: 17, borderWidth: 1, borderColor: '#e2ebe8', shadowColor: '#17324d', shadowOffset: { width: 0, height: 5 }, shadowOpacity: 0.08, shadowRadius: 14, elevation: 3 },
  calendarToolbar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  calendarIconButton: { minWidth: 35, height: 35, borderRadius: 10, backgroundColor: '#edf4f1', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 9 },
  calendarTodayText: { color: '#3e7185', fontSize: 12, fontWeight: '800' },
  monthNavigation: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  calendarMonthTitle: { color: '#17324d', fontSize: 17, fontWeight: '800' },
  calendarWeekRow: { flexDirection: 'row', marginTop: 20, marginBottom: 7 },
  calendarWeekday: { flex: 1, textAlign: 'center', color: '#91a09e', fontSize: 11, fontWeight: '800' },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  calendarDayCell: { width: '14.285%', height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: 13 },
  calendarSelectedDay: { backgroundColor: '#3e7185' },
  calendarDayNumber: { color: '#405366', fontSize: 14, fontWeight: '600' },
  calendarSelectedDayText: { color: '#ffffff', fontWeight: '800' },
  calendarAppointmentMark: { width: 5, height: 5, borderRadius: 3, backgroundColor: '#d97745', marginTop: 3 },
  calendarSelectedMark: { backgroundColor: '#ffffff' },
  selectedDayHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', borderTopWidth: 1, borderTopColor: '#edf1ef', marginTop: 12, paddingTop: 15 },
  selectedDayLabel: { color: '#91a09e', fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.6 },
  selectedDayTitle: { color: '#17324d', fontSize: 16, fontWeight: '800', marginTop: 3 },
  selectedDayCount: { color: '#3e7185', fontSize: 12, fontWeight: '700' },
  hourAgenda: { marginTop: 12 },
  hourRow: { minHeight: 48, flexDirection: 'row', borderTopWidth: 1, borderTopColor: '#f0f3f1' },
  hourRowContent: { flex: 1, justifyContent: 'center' },
  emptyHourLine: { borderTopWidth: 1, borderTopColor: '#edf1ef', borderStyle: 'dashed' },
  hourAppointment: { flexDirection: 'row', alignItems: 'center', paddingVertical: 7 },
  hourLabel: { width: 65, color: '#3e7185', fontSize: 12, fontWeight: '800' },
  hourAppointmentBody: { flex: 1, borderLeftWidth: 2, borderLeftColor: '#d97745', paddingLeft: 11 },
  hourAppointmentTitle: { color: '#17324d', fontSize: 14, fontWeight: '800' },
  hourAppointmentVenue: { color: '#7b8794', fontSize: 12, marginTop: 3 },
  emptyScheduleText: { color: '#8b9aaa', fontSize: 13, paddingVertical: 10 },
  upcomingHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 26, marginBottom: 13 },
  upcomingTitle: { color: '#17324d', fontSize: 21, fontWeight: '800' },
  upcomingSubtitle: { color: '#7b8794', fontSize: 12, marginTop: 3 },
  upcomingCount: { color: '#ffffff', backgroundColor: '#d97745', minWidth: 28, height: 28, borderRadius: 14, textAlign: 'center', paddingTop: 6, fontSize: 12, fontWeight: '800' },
  appointmentSearchWrap: { height: 46, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 13, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#dfe8e4', borderRadius: 12 },
  appointmentSearch: { flex: 1, color: '#17324d', fontSize: 14 },
  filterOptions: { flexDirection: 'row', gap: 8, marginVertical: 12 },
  filterOption: { paddingHorizontal: 13, paddingVertical: 8, borderRadius: 9, backgroundColor: '#e7eeeb' },
  filterOptionActive: { backgroundColor: '#17324d' },
  filterOptionText: { color: '#657571', fontSize: 12, fontWeight: '700' },
  filterOptionTextActive: { color: '#ffffff' },
  upcomingAppointment: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#ffffff', borderRadius: 15, padding: 13, marginBottom: 10, borderWidth: 1, borderColor: '#e2ebe8' },
  upcomingDateBox: { width: 48, height: 55, borderRadius: 11, backgroundColor: '#edf4f1', alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  upcomingDateMonth: { color: '#3e7185', fontSize: 10, fontWeight: '800' },
  upcomingDateDay: { color: '#17324d', fontSize: 22, fontWeight: '800', marginTop: 1 },
  upcomingAppointmentInfo: { flex: 1 },
  upcomingAppointmentTitle: { color: '#17324d', fontSize: 15, fontWeight: '800' },
  upcomingAppointmentMeta: { color: '#3e7185', fontSize: 12, marginTop: 4 },
  upcomingAppointmentMission: { color: '#7b8794', fontSize: 12, marginTop: 3 },
  emptyListText: { color: '#8b9aaa', backgroundColor: '#ffffff', borderRadius: 14, padding: 20, textAlign: 'center', fontSize: 13 },
  scheduleModalBackdrop: { flex: 1, backgroundColor: 'rgba(23, 50, 77, 0.42)', justifyContent: 'center', padding: 20 },
  scheduleModalCard: { backgroundColor: '#ffffff', borderRadius: 20, padding: 20, borderWidth: 1, borderColor: '#e2ebe8' },
  modalHeadingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  modalEyebrow: { color: '#3e7185', fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.7 },
  scheduleModalTitle: { color: '#17324d', fontSize: 22, fontWeight: '800', marginTop: 4 },
  scheduleModalDate: { color: '#d97745', fontSize: 13, fontWeight: '800', marginTop: 17 },
  scheduleModalMission: { color: '#405366', fontSize: 15, fontWeight: '700', marginTop: 14 },
  scheduleModalDetail: { color: '#526b70', fontSize: 13, marginTop: 12 },
  scheduleModalReason: { color: '#667781', fontSize: 13, lineHeight: 19, marginTop: 16 },
  scheduleModalNotes: { color: '#7b8794', fontSize: 12, fontStyle: 'italic', marginTop: 11 },
  modalCloseButton: { alignItems: 'center', justifyContent: 'center', height: 44, borderRadius: 11, backgroundColor: '#17324d', marginTop: 20 },
  modalCloseButtonText: { color: '#ffffff', fontSize: 14, fontWeight: '800' },
});

export default globalStyles;